spring.application.name=MySpringbootLab
myprop.username=springboot
myprop.port=${random.int(1,100)}
logging.level.com.example=DEBUG
server.port=8081

# 현재 활성화된 Profile 값 설정 test|prod
spring.profiles.active=prod
